---
server:
  host: 0.0.0.0
  port: 4400
clients:
  autobrr:
    host: http://localhost:7474
    apikey: API_KEY
  radarr:
    host: http://localhost:7878
    apikey: API_KEY
    filters:
      - 15
  sonarr:
    host: http://localhost:8989
    apikey: API_KEY
    filters:
      - 14
